name: Toolchain-cache
on:
  # schedule:
  #   - cron: '51 10 28 * *'
  # runs at 10:51 UTC every 28th day of each month
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Debug session enabled'
        required: false
        default: true
        type: boolean

jobs:
  build:
    if: ${{ true }}
    name: Builds toolchain
    runs-on: ubuntu-latest
    container: alpine:edge
    defaults:
      run:
        shell: bash
    steps:
    - name: "get basic Packages"
      if: ${{ job.container }}
      shell: sh
      run: |
        apk update && apk upgrade
        apk add bash nano-syntax iproute2 util-linux-misc iproute2 \
          cmake file git make tar xz nano-syntax
        # set PATH like in Ubuntu
        echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV
        # this seems to be needed when running in a container (beause of UID mismatch??)
        git config --global --add safe.directory '*'
        
    - name: "ğŸ”§ Prepare debug session"
      if: github.event.inputs.debug_enabled == 'true'
      run: |
        wget https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/posh-linux-amd64 -O /usr/local/bin/oh-my-posh
        chmod +x /usr/local/bin/oh-my-posh
        wget -q https://github.com/okibcn/miniU/raw/main/Github_Linux/.nanorc -O ~/.nanorc
        wget -q https://github.com/okibcn/miniU/raw/main/Github_Linux/profile.sh -O ~/.zshrc
        cp /etc/bash.bashrc ~ || true
        cat ~/.zshrc >> ~/bash.bashrc 
        cp ~/bash.bashrc /etc/bash.bashrc -f

    - name: "ğŸ Debug session"
      uses: mxschmitt/action-tmate@v3
      if: github.event.inputs.debug_enabled == 'true'
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ## More info at https://til.simonwillison.net/github-actions/debug-tmate
        ##           or https://github.com/mxschmitt/action-tmate

    - name: "ğŸ”§ Build"
      if: ${{ false }}
      run: |
        echo " This shell: $SHELL"
        git clone https://github.com/mstorsjo/llvm-mingw.git llvm
        cd llvm
